name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Java Set-Up
        # Java 8 by default, doesn't really matter for us
      - uses: actions/setup-java@v2

        with:
          distribution: "adopt"
          java-version: "8"

      - name: Gradle Build
        run: /bin/sh ./gradlew build

      - name: Gradle Publish
        run: /bin/sh ./gradlew -Pjourneymap.user=${{ secrets.JOURNEYMAP_USER }} -Pjourneymap.password=${{ secrets.JOURNEYMAP_PASSWORD }} publish
